Feature/check outbox if file exists GDEV-276 // GDEV-277
ghga-de/drs3 pull request #3
Opened 2021-11-26 15:05 UTC by MoritzHahn1337

Title for squash and merge:
```
Checks outbox if file exists after download request
```

Description for squash and merge:
```
Checks the outbocks after an API download request, if a file exists
Returns a presigned url if it does exist
Returns a 202 Statement and publishes a non_staged_file_request topic if not
```

2021-11-26 15:19 UTC, MoritzHahn1337 commented
Do not merge, Tests are still missing

2021-12-02 16:18 UTC, KerstenBreuer requested changes
Looks good, maybe just a couple of re-arrangements.

Please let me know if you want to chat about it at any time.

2021-12-02 16:18 UTC, KerstenBreuer commented on drs3/api/main.py
> +        )
Could we put this into the core subpackage as a separate function? We may also consider to remove the pyramid exception (HTTPNotFound) and just let it throw the DrsObjectNotFoundError. We can still "mention" it in the core function just to make sure everybody reading this code understands what can happen, e.g. like this:
```
# check if DRS object is registered in the database
# and forward the error if not:
try:
    db_object_info = database.get_drs_object(object_id)
except DrsObjectNotFoundError:
    raise
```

The DrsObjectNotFoundError can then be translated to the HTTP error in the view function as you did here.


The last part of publishing a message should however not be part of the core function directly. One possibility would be to give the core function and argument of type Callable called something like "make_stage_request". Then when calling the core function in the view function we hand over the appropriate publishing function. The publishing function then receives a pydantic model of the DRS object and constructs and sends the message.

Like this we would achieve a nice separation between business logic and the API.

2021-12-02 16:18 UTC, KerstenBreuer commented on drs3/dao/db.py
> +psql_connector = SyncPostgresqlConnector(CONFIG)
I think this can be removed since the SyncPostgresqlConnector is now defined in the PostgresDatabase class based on the config.

2021-12-02 16:18 UTC, KerstenBreuer commented on drs3/pubsub/publish.py
> +        service_name="drs3",
I am sorry, I have reworked this part in the chassis lib. Now the `connection_params` and `service_name` are replaced by an instance of a PubSubConfigBase.

2021-12-02 16:18 UTC, KerstenBreuer commented on drs3/api/main.py
> +            )
what is this part doing?

2021-12-06 09:09 UTC, MoritzHahn1337 commented on drs3/api/main.py
> +    config: Config = CONFIG
I'll try this:

https://docs.pylonsproject.org/projects/pyramid/en/latest/api/testing.html

2021-12-10 11:14 UTC, KerstenBreuer approved these changes
Very good, when applying following small changes this can be merged.

2021-12-10 11:14 UTC, KerstenBreuer commented on drs3/pubsub/schemas/non_staged_file_requested.json
> +    },
You are right by not using these fields. They probably should be removed from the schema entirely. I will take care of that.

2021-12-10 12:48 UTC, merged