Feature/write file information to outbox repo gdev 280
ghga-de/drs3 pull request #4
Opened 2021-11-30 20:09 UTC by MoritzHahn1337

Title for squash and merge:
```
Subscribes to file_staged_for_download, updates database entry, if ncessary
```

Description for squash and merge:
```
Subscribes to file_staged_for_download
Checks, if the file really exists in outbox
Updates the file related information in the database, if necessary
```

2021-11-30 20:12 UTC, MoritzHahn1337 commented
Tests also still missing, do not merge

2021-12-02 17:08 UTC, KerstenBreuer requested changes
Initially, I thought we would have to keep a boolean flag in the database to check if a file is present in the storage or not. However, your implementation is right: We can get this info just by looking directly at the storage outbox. Maybe we have to re-think if we right now need the "file_staged_for_download" topic at all?

Let's discuss that tomorrow.

2021-12-02 17:08 UTC, KerstenBreuer commented on drs3/pubsub/subscribe.py
> +                database.update_drs_object(db_object_info)
Would the md5checksum, the size, and the registration date really change upon staging? (Once we are re-encrypting for an individual user that will be the case and we have to maintain infos on user-specific DRS-object copies.)

2021-12-14 11:59 UTC, KerstenBreuer approved these changes
Looks all right

2021-12-14 11:59 UTC, KerstenBreuer commented on tests/unit/test_pubsub.py
> +    print(psql_fixture.existing_file_infos[0])
```suggestion
```
Leftover debug statement?

2021-12-14 12:20 UTC, merged